### ISSUE TITLE
Numeric Overflow when calculating gas in `createTokenBridge-ethers`

### ISSUE THREAD

**Issue by tadad** [OffchainLabs/arbitrum-orbit-sdk#157]
When using gas overrides for retryables in `createTokenBridge-ethers` - the gas calculations are liable to overflow because they are converted to normal javascript numbers instead of strings and then into BigNumbers.

Here is a quick script I wrote to reproduce this:
```
import { JsonRpcProvider } from '@ethersproject/providers'
import { RollupAdminLogic__factory } from '@arbitrum/sdk/dist/lib/abi/factories/RollupAdminLogic__factory'
import { defineChain, createPublicClient, http, Address } from 'viem'
import { privateKeyToAccount } from 'viem/accounts'
import { createTokenBridgePrepareTransactionRequest } from '@arbitrum/orbit-sdk';
import { sanitizePrivateKey } from '@arbitrum/orbit-sdk/utils'

function createPublicClientFromChainInfo({
  id,
  name,
  rpcUrl,
}: {
  id: number
  name: string
  rpcUrl: string
}) {
  const chain = defineChain({
    id: id,
    network: name,
    name: name,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
    rpcUrls: {
      default: {
        http: [rpcUrl],
      },
      public: {
        http: [rpcUrl],
      },
    },
    testnet: true,
  })

  return createPublicClient({ chain, transport: http() })
}

async function main() {
  const baseChainRpc = 'https://public.stackup.sh/api/v1/node/ethereum-sepolia	'
  const childChainRpc = 'https://rpc-safe-arb-final-test-ldcnti87cp.t.conduit-stg.xyz'
  const rollupAddress = "0xAB903c1E98694F23B12C710fEc6FEa8f0696d4b3"
  const baseChainDeployerKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"



  const l1Provider = new JsonRpcProvider(baseChainRpc)
  const l1NetworkInfo = await l1Provider.getNetwork()

  const l2Provider = new JsonRpcProvider(childChainRpc)
  const l2NetworkInfo = await l2Provider.getNetwork()

  const deployer = privateKeyToAccount(sanitizePrivateKey(baseChainDeployerKey))
  const rollup = RollupAdminLogic__factory.connect(rollupAddress, l1Provider)

  const parentChainPublicClient = createPublicClientFromChainInfo({
    id: l1NetworkInfo.chainId,
    name: l1NetworkInfo.name,
    rpcUrl: baseChainRpc,
  })

  const orbitChainPublicClient = createPublicClientFromChainInfo({
    id: l2NetworkInfo.chainId,
    name: l2NetworkInfo.name,
    rpcUrl: childChainRpc,
  })

  const txRequest = await createTokenBridgePrepareTransactionRequest({
    params: {
      rollup: rollupAddress as Address,
      rollupOwner: deployer.address,
    },
    parentChainPublicClient,
    orbitChainPublicClient,
    account: deployer.address,
    gasOverrides: {
      gasLimit: {
        percentIncrease: 1000n,
      },
    },
    retryableGasOverrides: {
      maxSubmissionCostForFactory: {
        percentIncrease: 1000n,
      },
      maxGasForFactory: {
        percentIncrease: 1000n,
      },
      maxSubmissionCostForContracts: {
        percentIncrease: 1000n,
      },
      maxGasForContracts: {
        percentIncrease: 1000n,
      },
    },
  })
}
main()
```

and the trace it produces:
```
Error: overflow [ See: https://links.ethers.org/v5-errors-NUMERIC_FAULT-overflow ] (fault="overflow", operation="toNumber", value="24748619995277248", code=NUMERIC_FAULT, version=bignumber/5.7.0)
    at Logger.makeError (/Users/drewtada/conduit/orbit-setup-script/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/drewtada/conduit/orbit-setup-script/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at throwFault (/Users/drewtada/conduit/orbit-setup-script/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:356:19)
    at BigNumber.toNumber (/Users/drewtada/conduit/orbit-setup-script/node_modules/@ethersproject/bignumber/src.ts/bignumber.ts:186:13)
    at createTokenBridgeGetInputs (/Users/drewtada/conduit/orbit-setup-script/node_modules/@arbitrum/orbit-sdk/dist/createTokenBridge-ethers.js:53:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createTokenBridgePrepareTransactionRequest (/Users/drewtada/conduit/orbit-setup-script/node_modules/@arbitrum/orbit-sdk/dist/createTokenBridgePrepareTransactionRequest.js:14:67)
    at async main (/Users/drewtada/conduit/orbit-setup-script/scripts/test.ts:65:21) {
  reason: 'overflow',
  code: 'NUMERIC_FAULT',
  fault: 'overflow',
  operation: 'toNumber',
  value: '24748619995277248'
}
```

Note that if you comment out the `gasOverrides` and `retryableGasOverrides` it should work

**Comment by spsjvc** [comment]
hey, good catch @tadad working on a fix and will release a version asap

**Comment by spsjvc** [comment]
@tadad published https://github.com/OffchainLabs/arbitrum-orbit-sdk/releases/tag/v0.17.2 which includes the fix, thank you once again for reporting!

**Comment by tadad** [comment]
thank you!
